
# CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/haze/AllLightCondition_last.pth.tar  --test_set 'snow' --image_folder 'final_results/snow/snow_cond_102w/' --sampling_timesteps 25 --grid_r 16

# CUDA_VISIBLE_DEVICES=1 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/raindrop/AllLightCondition_last.pth.tar  --test_set 'raindrop' --image_folder 'final_results/raindrop/raindrop_cond_108w/' --sampling_timesteps 25 --grid_r 16

# CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/rain/AllLightCondition_last.pth.tar  --test_set 'rain' --image_folder 'final_results/rain/rain_cond_102w/' --sampling_timesteps 25 --grid_r 16
# CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/haze/AllLightCondition_last.pth.tar  --test_set 'snow' --image_folder 'final_results/snow/snow_cond_102w/' --sampling_timesteps 25 --grid_r 16
# CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/haze/AllLightCondition_last.pth.tar  --test_set 'snow' --image_folder 'final_results/snow/snow_cond_102w/' --sampling_timesteps 25 --grid_r 16

# CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/haze/AllLightCondition_last.pth.tar  --test_set 'snow' --image_folder 'final_results/snow/snow_cond_102w/' --sampling_timesteps 25 --grid_r 16




# CUDA_VISIBLE_DEVICES=0 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/snow11k/AllLightCondition_ddpm920000.pth.tar  --test_set 'real_weather' --image_folder 'final_results/real_weather/real_snow/snow11k_cond_92w/' --sampling_timesteps 25 --grid_r 16 --test_input_path ../../data/real_weather/real_snow/test/input --test_input_sci_path ../../data/real_weather/real_snow/test/sci_difficult_illu_correct
# CUDA_VISIBLE_DEVICES=1 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/haze/AllLightCondition_ddpm1180000.pth.tar  --test_set 'real_weather' --image_folder 'final_results/real_weather/realhaze/haze_cond_118w/' --sampling_timesteps 25 --grid_r 16 --test_input_path ../../data/realhaze-RESIDE/Unannotated\ Real-world\ Hazy\ Images --test_input_sci_path ../../data/real_weather/realhaze/test/sci_difficult_illu_correct
# CUDA_VISIBLE_DEVICES=2 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/fog/AllLightCondition_ddpm1400000.pth.tar  --test_set 'real_weather' --image_folder 'final_results/real_weather/realfog/fog_cond_140w/' --sampling_timesteps 25 --grid_r 16 --test_input_path ../../data/realfog-iphone14pro  --test_input_sci_path ../../data/real_weather/realfog/test/sci_difficult_illu_correct
CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/raindrop/AllLightCondition_ddpm1420000.pth.tar  --test_set 'real_weather' --image_folder 'final_results/real_weather/realraindrop/raindrop_cond_142w/' --sampling_timesteps 25 --grid_r 16 --test_input_path ../../data/realraindrop-iphone14pro  --test_input_sci_path ../../data/real_weather/realraindrop/test/sci_difficult_illu_correct/
CUDA_VISIBLE_DEVICES=3 python eval_diffusion.py --config "all_light_condition.yml" --resume ckpt/lol_blur_noise/AllLightCondition_ddpm300000.pth.tar  --test_set 'real_weather' --image_folder 'final_results/real_weather/realblur/lol_blur_noise_cond_30w/' --sampling_timesteps 25 --grid_r 16 --test_input_path ../../data/realblur-iphone14pro --test_input_sci_path ../../data/real_weather/realblur/test/sci_difficult_illu_correct  