# python train_diffusion.py --config "lol_guided.yml" --image_folder='results/lol1_guided_illu_snr'
# python train_diffusion.py --config "lol_guided.yml" --resume 'ckpt/WeatherDiff64.pth.tar' --image_folder='results/lol1_guided'

# CUDA_VISIBLE_DEVICES=0 python eval_diffusion.py --config "lol_guided.yml" \
#  --resume 'ckpt/lolv1_guided_illu_snr/LOL_guided_ddpm_50000.pth.tar' --test_set 'lol_guided' \
#  --image_folder 'results/lol_guided_illu_snr_test/' --sampling_timesteps 25 --grid_r 16

# CUDA_VISIBLE_DEVICES=0 python eval_diffusion.py --config "lol_guided.yml" \
#  --resume 'ckpt/lolv1_guided_illu/LOL_guided_ddpm_50000.pth.tar' --test_set 'lol_guided' \
#  --image_folder 'results/lol_guided_illu_test/' --sampling_timesteps 25 --grid_r 16

# CUDA_VISIBLE_DEVICES=0 python eval_diffusion.py --config "lol_guided.yml" \
#  --resume 'ckpt/lolv1_guided_snr/LOL_guided_ddpm_50000.pth.tar' --test_set 'lol_guided' \
#  --image_folder 'results/lol_guided_snr_test/' --sampling_timesteps 25 --grid_r 16

data:
    dataset: "LOL_guided"
    image_size: 64
    channels: 3
    num_workers: 32
    data_dir: "/apdcephfs_cq2/share_1290939/feiiyin/Lowlevel/data/LOL-v1/"
    conditional: True
    ckpt_path: "ckpt/lolv1_guided_illu_snr/"
    
model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, 32]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 16
    n_epochs: 1775
    n_iters: 2000000
    snapshot_freq: 10000
    validation_freq: 10000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001

