# python train_diffusion.py --config "lolv2_syn.yml" --resume 'ckpt/WeatherDiff64.pth.tar' --image_folder='results/lol2syn'
# CUDA_VISIBLE_DEVICES=2 python eval_diffusion.py --config "lolv2_syn.yml" \
#  --resume '/home/cyf20/code/rrddln/LowLightDiffusion/ckpt/LOLv2_syn_ddpm_2090000.pth.tar' --test_set 'lolv2_syn' \
#  --image_folder 'results/lolv2syn_baseline_test' --sampling_timesteps 25 --grid_r 16

data:
    dataset: "LOLv2_syn"
    image_size: 64
    channels: 3
    num_workers: 32
    data_dir: "/home/cyf20/datasets/LOL-v2/Synthetic"
    conditional: True
    ckpt_path: "ckpt/lolv2_syn"
    
model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 16
    n_epochs: 3500
    n_iters: 4000000
    snapshot_freq: 10000
    validation_freq: 10000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001

